spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/demo
    username: postgres
    password: postgres
  jpa:
    show-sql: true
#    database-platform: com.guilherme.miguel.postgresdemo.config.hibernate.dialect.JSONBPostgreSQLDialect
    hibernate:
      ddl-auto: create-drop
